In [1]:
import pandas as pd
import streamlit as st
import plotly.express as px
import altair as alt
import os

@st.cache_data
def load_data():
    df = pd.read_csv("perda_poder_compra_habitacao_2018_2025.csv")
    return df

2026-03-08 17:38:22.628 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [2]:
ncaminho = os.path.expanduser("~/Desktop/perda_poder_compra_habitacao_2018_2025.csv")
df = pd.read_csv(caminho)
st.write("Dados carregados:", df.shape[0], "linhas")

NameError: name 'caminho' is not defined

In [ ]:
df = pd.read_csv("C:/Users/LENOVO i5 Gaming/Desktop/perda_poder_compra_habitacao_2018_2025.csv")

st.write("✅ Dados carregados:", df.shape[0], "linhas")
df.head()

,pais,ano,preco_medio_habitacao_usd,salario_medio_anual_usd,salario_medio_mensal_usd,inflacao_anual_pct,preco_rendimento_ratio
0,Portugal,2018,210000,24000,2000,1.2,8.75
1,Portugal,2019,225000,24500,2042,0.3,9.18
2,Portugal,2020,240000,25000,2083,0.0,9.60
3,Portugal,2021,270000,25500,2125,1.3,10.59
4,Portugal,2022,300000,25800,2150,7.8,11.63

In [ ]:
@st.cache_data
def load_data():
    # Caminho completo para o arquivo na pasta Downloads
    caminho_arquivo = os.path.expanduser("~/Downloads/perda_poder_compra_habitacao_2018_2025.csv")
    df = pd.read_csv(caminho_arquivo)
    return df

# Debug: verificar se o arquivo existe
print(os.path.exists(os.path.expanduser("~/Downloads/perda_poder_compra_habitacao_2018_2025.csv")))

# Carregar os dados
df = load_data()

2026-03-03 14:02:02.125 No runtime found, using MemoryCacheStorageManager

True

In [ ]:
# Filtro de período
ano_inicio, ano_fim = st.select_slider(
    "Selecione o período:",
    options=sorted(df["ano"].unique()),
    value=(df["ano"].min(), df["ano"].max())
)

df_filtrado = df[(df["ano"] >= ano_inicio) & (df["ano"] <= ano_fim)]

# Filtro de países
paises = st.multiselect(
    "Selecione os países:",
    df_filtrado["pais"].unique(),
    default=df_filtrado["pais"].unique()
)

df_filtrado = df_filtrado[df_filtrado["pais"].isin(paises)]

In [ ]:
df_filtrado.head()

,pais,ano,preco_medio_habitacao_usd,salario_medio_anual_usd,salario_medio_mensal_usd,inflacao_anual_pct,preco_rendimento_ratio
0,Portugal,2018,210000,24000,2000,1.2,8.75
1,Portugal,2019,225000,24500,2042,0.3,9.18
2,Portugal,2020,240000,25000,2083,0.0,9.60
3,Portugal,2021,270000,25500,2125,1.3,10.59
4,Portugal,2022,300000,25800,2150,7.8,11.63

In [ ]:
# Usar o container inteiro
grafico_preco = alt.Chart(df_filtrado).mark_line(point=True).encode(
    x="ano:O",
    y="preco_medio_habitacao_usd:Q",
    color="pais:N",
    tooltip=["pais", "ano", "preco_medio_habitacao_usd"]
).properties(
    width='container',  # Usa toda a largura disponível
    height=400
).interactive()

st.altair_chart(grafico_preco, use_container_width=True)
grafico_preco

c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [ ]:
st.subheader("📊 Evolução da Inflação Anual (%)")

grafico_inflacao = alt.Chart(df_filtrado).mark_line(point=True).encode(
    x="ano:O",
    y="inflacao_anual_pct:Q",
    color="pais:N",
    tooltip=["pais", "ano", "inflacao_anual_pct"]
).properties(
    width='container',
).interactive()

st.altair_chart(grafico_inflacao, use_container_width=True)
grafico_inflacao

c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [ ]:
st.subheader("💰 Evolução do Salário Médio Anual (USD)")

grafico_salario = alt.Chart(df_filtrado).mark_line(point=True).encode(
    x="ano:O",
    y="salario_medio_anual_usd:Q",
    color="pais:N",
    tooltip=["pais", "ano", "salario_medio_anual_usd"]
).properties(
    width='container',
).interactive()

st.altair_chart(grafico_salario, use_container_width=True)
grafico_salario

c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [ ]:
st.subheader("🏠 Indicador de Acessibilidade Habitacional (Preço / Rendimento)")

grafico_ratio = alt.Chart(df_filtrado).mark_line(point=True).encode(
    x="ano:O",
    y="preco_rendimento_ratio:Q",
    color="pais:N",
    tooltip=["pais", "ano", "preco_rendimento_ratio"]
).properties(
    width='container',
).interactive()

st.altair_chart(grafico_ratio, use_container_width=True)
grafico_ratio

c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\utils\core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [ ]:
from vega_datasets import data

st.subheader("🌎 Mapa Mundial")

world = alt.topo_feature(data.world_110m.url, "countries")

pais_selecionado = st.selectbox(
    "Selecione um país para destacar:",
    df["pais"].unique()
)

mapa = alt.Chart(world).mark_geoshape(
    stroke="black"
).encode(
    color=alt.condition(
        alt.datum.name == pais_selecionado,
        alt.value("orange"),
        alt.value("lightgray")
    ),
    tooltip=["name:N"]
).project("naturalEarth1").properties(
    width=1000,
    height=500
)

st.altair_chart(mapa, use_container_width=True)
mapa

2026-03-03 14:02:02.598 Session state does not function when running a script without `streamlit run`

alt.Chart(...)

In [ ]:
# País para destacar
pais_selecionado = "Portugal"  # Mude para outro país do seu df

world = alt.topo_feature(data.world_110m.url, "countries")

# Usando selection
selecao = alt.selection(
    type="single",
    on="click",
    empty="none"
)

mapa = alt.Chart(world).mark_geoshape(
    stroke='white',
    strokeWidth=0.5
).encode(
    color=alt.condition(
        selecao,
        alt.value("orange"),
        alt.value("lightgray")
    ),
    tooltip=alt.Tooltip('properties.name:N')  # ← Corrigido!
).add_params(
    selecao
).properties(
    width=700,
    height=450
).project(
    type='naturalEarth1'
)

mapa

c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\utils\deprecation.py:65: AltairDeprecationWarning: 'selection' is deprecated.
   Use 'selection_point()' or 'selection_interval()' instead; these functions also include more helpful docstrings.
  warnings.warn(message, AltairDeprecationWarning, stacklevel=1)
c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\vegalite\v5\api.py:425: AltairDeprecationWarning: The types 'single' and 'multi' are now
        combined and should be specified using "selection_point()".
  warnings.warn(
c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\vegalite\v5\api.py:362: AltairDeprecationWarning: The value of 'empty' should be True or False.
  warnings.warn(

alt.Chart(...)

In [6]:
# Precisa ter estas linhas antes no seu código:
from vega_datasets import data
world = alt.topo_feature(data.world_110m.url, "countries")

selecao = alt.selection(
    type="single",
    on="click",
    empty="none"
)

# Mapa com fundo azul escuro:
mapa = alt.Chart(world).mark_geoshape(
    stroke='white',
    strokeWidth=0.5
).encode(
    color=alt.condition(
        selecao,
        alt.value("orange"),
        alt.value("lightgray")
    ),
    tooltip=alt.Tooltip('properties.name:N')
).add_params(
    selecao
).properties(
    width=700,
    height=450
).project(
    type='naturalEarth1'
).configure_view(
    fill='#0d3b66'
)
mapa

c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\utils\deprecation.py:65: AltairDeprecationWarning: 'selection' is deprecated.
   Use 'selection_point()' or 'selection_interval()' instead; these functions also include more helpful docstrings.
  warnings.warn(message, AltairDeprecationWarning, stacklevel=1)
c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\vegalite\v5\api.py:425: AltairDeprecationWarning: The types 'single' and 'multi' are now
        combined and should be specified using "selection_point()".
  warnings.warn(
c:\Users\LENOVO i5 Gaming\anaconda3\Lib\site-packages\altair\vegalite\v5\api.py:362: AltairDeprecationWarning: The value of 'empty' should be True or False.
  warnings.warn(

alt.Chart(...)